version: "3.8"

services:
  star_shop_app:
    build: .
    container_name: star_shop_app
    command: >
      sh -c "pipenv run alembic upgrade head &&
             pipenv run python main.py"
    env_file:
      - .env
    depends_on:
      - star_shop_database
      - star_shop_redis
    networks:
      - star_shop_dev
    volumes:
      - .:/app
    restart: unless-stopped

  star_shop_database:
    container_name: star_shop_database
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=StarAdmUser
      - POSTGRES_PASSWORD=Star1Adm1User2
      - POSTGRES_DB=StarDatabaseName
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - star_shop_dev
    restart: always

  star_shop_redis:
    image: redis:alpine
    container_name: star_shop_redis
    volumes:
      - task-storage:/data
    ports:
      - "6378:6379"
    env_file:
      - .env
    networks:
      - star_shop_dev
    restart: unless-stopped

networks:
  star_shop_dev:
    name: star_shop_dev_network
    driver: bridge

volumes:
  postgres_data: null
  task-storage: null