version: "3.8"

services:
#  faq_app:
#    build: .
#    container_name: faq_app
#    env_file:
#      - .env
#    depends_on:
#      - faq_database
#      - faq_redis
#      - faq_celery
#    networks:
#      - faq_dev
#    volumes:
#      - .:/app
#    restart: unless-stopped

  faq_database:
    container_name: faq_database
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - faq_dev
    restart: always

  faq_redis:
    image: redis:alpine
    container_name: faq_redis
    volumes:
      - task-storage:/data
    ports:
      - "6379:6379"
    env_file:
      - .env
    networks:
      - faq_dev
    restart: unless-stopped

networks:
  faq_dev:
    name: faq_dev_network
    driver: bridge

volumes:
  postgres_data: null
  task-storage: null