version: "3.8"

services:
  contest_app:
    build: .
    container_name: contest_app
    command: >
      sh -c "pipenv run alembic upgrade head &&
             pipenv run python main.py"
    env_file:
      - .env
    depends_on:
      - contest_database
      - contest_redis
    networks:
      - contest_dev
    volumes:
      - .:/app
    restart: unless-stopped

  contest_database:
    container_name: contest_database
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=StarAdmUser
      - POSTGRES_PASSWORD=Star1Adm1User2
      - POSTGRES_DB=StarDatabaseName
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - contest_dev
    restart: always

  contest_redis:
    image: redis:alpine
    container_name: contest_redis
    volumes:
      - task-storage:/data
    ports:
      - "6378:6379"
    env_file:
      - .env
    networks:
      - contest_dev
    restart: unless-stopped

networks:
  contest_dev:
    name: contest_dev_network
    driver: bridge

volumes:
  postgres_data: null
  task-storage: null