"""empty message

Revision ID: 16658d731190
Revises: 17c5f61b4ec7
Create Date: 2024-12-27 09:25:13.021052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16658d731190'
down_revision: Union[str, None] = '17c5f61b4ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prizes', sa.Column('winner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prizes', 'winner')
    # ### end Alembic commands ###
